-- Baza: Rus Tili — database schema for Supabase (Postgres)
-- Run this once in your Supabase project's SQL Editor (Dashboard → SQL Editor → New query)

create table if not exists lessons (
  id integer primary key,
  t text not null,
  tr text default '',
  cat text default '',
  lv text not null,
  p jsonb not null default '[]',
  sort_order integer not null default 0
);

create table if not exists users (
  id bigserial primary key,
  tg_id bigint unique not null,
  first_name text default '',
  last_name text default '',
  username text default '',
  xp integer not null default 0,
  streak integer not null default 0,
  last_day text default '',
  done jsonb not null default '[]',
  words jsonb not null default '[]',
  banned boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_users_xp on users (xp desc);
create index if not exists idx_users_tg_id on users (tg_id);

-- Row Level Security: lock the tables down completely.
-- All access goes through our serverless functions using the service-role key,
-- never directly from the browser, so RLS should block anonymous/public access entirely.
alter table lessons enable row level security;
alter table users enable row level security;
-- (No policies added on purpose — default-deny. The service role key bypasses RLS.)

-- Seed data: your current 25 lessons
INSERT INTO lessons (id, t, tr, cat, lv, p, sort_order) VALUES
(1, 'Rus alifbosi: unlilar', 'Гласные буквы', 'Noldan boshlash', 'basics', '[{"id": 901, "ru": "А а", "uz": "A tovushi", "ctx": "мама (ona) soʻzida", "gr": "Ochiq va keng talaffuz qilinadi, oʻzbekcha A ga oʻxshaydi."}, {"id": 902, "ru": "О о", "uz": "O tovushi", "ctx": "окно (deraza) soʻzida", "gr": "Urgʻu ostida O, urgʻusiz A kabi talaffuz qilinadi."}, {"id": 903, "ru": "И и", "uz": "I tovushi", "ctx": "игра (oʻyin) soʻzida", "gr": "Doim yumshoq va tor I tovushi."}, {"id": 904, "ru": "У у", "uz": "U tovushi", "ctx": "утро (tong) soʻzida", "gr": "Lablar yumaloq holatda talaffuz qilinadi."}, {"id": 905, "ru": "Ы ы", "uz": "Qattiq I tovushi", "ctx": "рыба (baliq) soʻzida", "gr": "Oʻzbek tilida ekvivalenti yoʻq, tilni orqaga tortib ayting."}, {"id": 906, "ru": "Э э", "uz": "E tovushi", "ctx": "это (bu) soʻzida", "gr": "Ochiq E tovushi, doim qattiq undoshdan keyin keladi."}, {"id": 907, "ru": "Я я", "uz": "Ya tovushi", "ctx": "я (men) soʻzida", "gr": "Й+А birikmasi, soʻz boshida Ya deb oʻqiladi."}]'::jsonb, 1),
(2, 'Rus alifbosi: undoshlar', 'Согласные буквы', 'Noldan boshlash', 'basics', '[{"id": 911, "ru": "Б б", "uz": "B tovushi", "ctx": "брат (aka/uka) soʻzida", "gr": "Oʻzbekcha B bilan bir xil talaffuz qilinadi."}, {"id": 912, "ru": "В в", "uz": "V tovushi", "ctx": "вода (suv) soʻzida", "gr": "Pastki lab yuqori tishga tegib talaffuz qilinadi."}, {"id": 913, "ru": "Г г", "uz": "G tovushi", "ctx": "город (shahar) soʻzida", "gr": "Qattiq G tovushi, oʻzbekcha G ga oʻxshaydi."}, {"id": 914, "ru": "Ж ж", "uz": "J tovushi", "ctx": "жизнь (hayot) soʻzida", "gr": "Doim qattiq talaffuz qilinadi, yumshamaydi."}, {"id": 915, "ru": "Р р", "uz": "Titroq R tovushi", "ctx": "работа (ish) soʻzida", "gr": "Til uchi tebranib talaffuz qilinadi."}, {"id": 916, "ru": "Х х", "uz": "X tovushi", "ctx": "хорошо (yaxshi) soʻzida", "gr": "Tomoqdan chiquvchi X tovushi."}, {"id": 917, "ru": "Ь", "uz": "Yumshatish belgisi", "ctx": "мать (ona) soʻzida", "gr": "Oʻzidan oldingi undoshni yumshatadi, alohida tovush emas."}]'::jsonb, 2),
(3, 'Olmoshlar va boʻlish feʼli', 'Местоимения и быть', 'Noldan boshlash', 'basics', '[{"id": 921, "ru": "Я", "uz": "Men", "ctx": "Birinchi shaxs birlik", "gr": "Doim bosh harf bilan yozilmaydi, faqat gap boshida."}, {"id": 922, "ru": "Ты", "uz": "Sen", "ctx": "Norasmiy muloqot", "gr": "Yaqin doʻstlar va bolalar bilan ishlatiladi."}, {"id": 923, "ru": "Вы", "uz": "Siz", "ctx": "Rasmiy muloqot", "gr": "Kattalar va notanishlar bilan ishlatiladi, koʻplik ham anglatadi."}, {"id": 924, "ru": "Он, она, оно", "uz": "U (erkak, ayol, neytral)", "ctx": "Uchinchi shaxs birlik", "gr": "Rus tilida jins otlarga ham tegishli."}, {"id": 925, "ru": "Мы, они", "uz": "Biz, ular", "ctx": "Koʻplik olmoshlari", "gr": "Mы=biz, они=ular."}, {"id": 926, "ru": "Я студент.", "uz": "Men talabaman.", "ctx": "Kasb yoki holatni aytish", "gr": "Rus tilida hozirgi zamonda \\\"boʻlmoq\\\" feʼli tushiriladi."}, {"id": 927, "ru": "Это дом.", "uz": "Bu uy.", "ctx": "Buyumni koʻrsatish", "gr": "Это=bu, jins va sonni oʻzgartirmaydi."}]'::jsonb, 3),
(4, 'Oddiy gap qurish', 'Простые предложения', 'Noldan boshlash', 'basics', '[{"id": 931, "ru": "Да.", "uz": "Ha.", "ctx": "Rozilik", "gr": "Eng qisqa javob."}, {"id": 932, "ru": "Нет.", "uz": "Yoʻq.", "ctx": "Rad etish", "gr": "Eng qisqa inkor."}, {"id": 933, "ru": "Я не знаю.", "uz": "Men bilmayman.", "ctx": "Bilmaslikni bildirish", "gr": "Не=emas/yoʻq, знаю=bilaman."}, {"id": 934, "ru": "Это хорошо.", "uz": "Bu yaxshi.", "ctx": "Fikr bildirish", "gr": "Sifat gapning oxirida keladi."}, {"id": 935, "ru": "Это плохо.", "uz": "Bu yomon.", "ctx": "Salbiy fikr", "gr": "плохо=yomon."}, {"id": 936, "ru": "У меня есть вопрос.", "uz": "Savolim bor.", "ctx": "Savol berishdan oldin", "gr": "У меня есть=mening bor, vопрос=savol."}, {"id": 937, "ru": "Спасибо большое!", "uz": "Katta rahmat!", "ctx": "Chuqur minnatdorchilik", "gr": "большое=katta, spasibo bilan birga ishlatiladi."}]'::jsonb, 4),
(5, 'Salomlashish', 'Приветствие', 'Kundalik hayot', 'beginner', '[{"id": 1, "ru": "Здравствуйте!", "uz": "Assalomu alaykum!", "ctx": "Rasmiy salomlashish", "gr": "Rasmiy shakl. Kattalar bilan ishlatiladi."}, {"id": 3, "ru": "Доброе утро!", "uz": "Xayrli tong!", "ctx": "Ertalab 12:00 gacha", "gr": "Доброе=yaxshi, утро=tong."}, {"id": 4, "ru": "Добрый день!", "uz": "Xayrli kun!", "ctx": "Kunduzi 12:00-18:00", "gr": "Добрый=yaxshi, день=kun."}, {"id": 5, "ru": "Добрый вечер!", "uz": "Xayrli kech!", "ctx": "18:00 dan keyin", "gr": "вечер=kech."}, {"id": 6, "ru": "Как дела?", "uz": "Ishlar qalay?", "ctx": "Hol-ahvol so''rash", "gr": "Как=qanday, дела=ishlar."}, {"id": 7, "ru": "Хорошо, спасибо.", "uz": "Yaxshi, rahmat.", "ctx": "Javob berish", "gr": "Хорошо=yaxshi, спасибо=rahmat."}, {"id": 8, "ru": "А у вас?", "uz": "Siz-chi?", "ctx": "Qaytarib so''rash — odob", "gr": "У вас=sizda. Qaytarib so''rash odob."}, {"id": 9, "ru": "До свидания!", "uz": "Xayr!", "ctx": "Rasmiy xayrlashish", "gr": "До=gacha, свидания=uchrashuv."}]'::jsonb, 5),
(6, 'Tanishish', 'Знакомство', 'Kundalik hayot', 'beginner', '[{"id": 11, "ru": "Меня зовут Али.", "uz": "Mening ismim Ali.", "ctx": "Ismni aytish", "gr": "Меня=meni, зовут=chaqiradi."}, {"id": 12, "ru": "Как вас зовут?", "uz": "Ismingiz nima?", "ctx": "Rasmiy so''rash", "gr": "вас=sizni (rasmiy)."}, {"id": 13, "ru": "Как тебя зовут?", "uz": "Isming nima?", "ctx": "Norasmiy so''rash", "gr": "тебя=seni (yoshlar bilan)."}, {"id": 14, "ru": "Приятно познакомиться!", "uz": "Tanishganimdan xursandman!", "ctx": "Birinchi uchrashuv", "gr": "Приятно=yoqimli, познакомиться=tanishmoq."}, {"id": 15, "ru": "Откуда вы?", "uz": "Siz qayerdansiz?", "ctx": "Kelib chiqishni so''rash", "gr": "Откуда=qayerdan."}, {"id": 17, "ru": "Я живу в Ташкенте.", "uz": "Men Toshkentda yashayman.", "ctx": "Yashash joyi", "gr": "живу=yashayman, в=da."}]'::jsonb, 6),
(7, 'Sonlar 1-20', 'Числа 1-20', 'Kundalik hayot', 'beginner', '[{"id": 21, "ru": "Один, два, три.", "uz": "Bir, ikki, uch.", "ctx": "Asosiy sonlar 1-3", "gr": "1=один, 2=два, 3=три."}, {"id": 26, "ru": "Двадцать.", "uz": "Yigirma.", "ctx": "20 soni", "gr": "20=двадцать."}, {"id": 27, "ru": "Сколько вам нужно?", "uz": "Sizga nechta kerak?", "ctx": "Miqdor so''rash", "gr": "Сколько=nechta, нужно=kerak."}, {"id": 28, "ru": "Мне нужно пять.", "uz": "Menga besh kerak.", "ctx": "Miqdor aytish", "gr": "Мне=menga."}]'::jsonb, 7),
(8, 'Vaqt va kunlar', 'Время и дни', 'Kundalik hayot', 'beginner', '[{"id": 29, "ru": "Который час?", "uz": "Soat necha?", "ctx": "Vaqt so''rash", "gr": "Который=qaysi."}, {"id": 30, "ru": "Сейчас три часа.", "uz": "Hozir soat uch.", "ctx": "Vaqt aytish", "gr": "Сейчас=hozir."}, {"id": 31, "ru": "Какой сегодня день?", "uz": "Bugun haftaning kuni?", "ctx": "Kun so''rash", "gr": "Какой=qanday, сегодня=bugun."}, {"id": 32, "ru": "Сегодня понедельник.", "uz": "Bugun dushanba.", "ctx": "Kun aytish", "gr": "понедельник=dushanba (haftaning birinchi kuni)."}, {"id": 33, "ru": "Завтра вторник.", "uz": "Ertaga seshanba.", "ctx": "Ertangi kun", "gr": "Завтра=ertaga."}, {"id": 34, "ru": "Во сколько?", "uz": "Soat nechada?", "ctx": "Vaqt belgilash", "gr": "Во=da (vaqt bilan)."}, {"id": 35, "ru": "В восемь утра.", "uz": "Ertalab soat sakkizda.", "ctx": "Aniq vaqt", "gr": "утра=ertalabning."}, {"id": 36, "ru": "Каждый день.", "uz": "Har kuni.", "ctx": "Doimiylik", "gr": "Каждый=har bir."}]'::jsonb, 8),
(9, 'Oilaviy hayot', 'Семья', 'Kundalik hayot', 'beginner', '[{"id": 37, "ru": "У вас есть дети?", "uz": "Farzandlaringiz bormi?", "ctx": "Oilaviy holat so''rash", "gr": "У вас есть=sizda bormi?"}, {"id": 38, "ru": "У меня двое детей.", "uz": "Mening ikki farzandim bor.", "ctx": "Javob berish", "gr": "двое=ikki (kollektiv son)."}, {"id": 40, "ru": "Мы живём вместе.", "uz": "Biz birga yashaymiz.", "ctx": "Turmush tarzi", "gr": "Мы=biz, вместе=birga."}, {"id": 41, "ru": "Я женат.", "uz": "Men uylanganman.", "ctx": "Oilaviy holat", "gr": "Faqat erkaklar uchun. Ayollar: Я замужем."}, {"id": 42, "ru": "Бабушка и дедушка.", "uz": "Buvi va buva.", "ctx": "Qarindoshlar", "gr": "и=va."}, {"id": 43, "ru": "У меня есть брат и сестра.", "uz": "Mening aka/uka va opa/singilim bor.", "ctx": "Qarindoshlar", "gr": "брат=aka/uka, сестра=opa/singil."}, {"id": 44, "ru": "Семья — это важно.", "uz": "Oila — bu muhim.", "ctx": "Fikr bildirish", "gr": "это=bu, важно=muhim."}]'::jsonb, 9),
(10, 'Kayfiyat va holatlar', 'Настроение', 'Kundalik hayot', 'beginner', '[{"id": 45, "ru": "Я рад!", "uz": "Men xursandman!", "ctx": "Hursandchilik", "gr": "рад=xursand (erkak). рада=xursand (ayol)."}, {"id": 47, "ru": "Я устал.", "uz": "Men charchadim.", "ctx": "Charchash", "gr": "устал=charchadi (erkak). устала=charchadi (ayol)."}, {"id": 48, "ru": "Мне холодно.", "uz": "Menga sovuq.", "ctx": "Sovuq hissi", "gr": "Sovuq his qilish."}, {"id": 49, "ru": "Мне жарко.", "uz": "Menga issiq.", "ctx": "Issiq hissi", "gr": "Issiq his qilish."}, {"id": 50, "ru": "Я не понимаю.", "uz": "Men tushunmayapman.", "ctx": "Tushunmaslik", "gr": "понимаю=tushunaman. Juda muhim!"}, {"id": 51, "ru": "Понятно.", "uz": "Tushunarli.", "ctx": "Tushunganni bildirish", "gr": "Qisqa va samarali javob."}, {"id": 52, "ru": "Извините, повторите, пожалуйста.", "uz": "Kechirasiz, qaytadan ayting.", "ctx": "Qayta so''rash", "gr": "3 ta muhim so''z."}]'::jsonb, 10),
(11, 'Ob-havo', 'Погода', 'Kundalik hayot', 'beginner', '[{"id": 53, "ru": "Какая сегодня погода?", "uz": "Bugun ob-havo qanday?", "ctx": "Ob-havo so''rash", "gr": "Какая=qanday, погода=ob-havo."}, {"id": 54, "ru": "Сегодня тепло.", "uz": "Bugun issiq.", "ctx": "Issiq kun", "gr": "тепло=issiq (harorat)."}, {"id": 55, "ru": "Сегодня холодно.", "uz": "Bugun sovuq.", "ctx": "Sovuq kun", "gr": "холодно=sovuq."}, {"id": 58, "ru": "Светит солнце.", "uz": "Quyosh chiqmoqda.", "ctx": "Quyoshli kun", "gr": "Светит=yoritmoqda."}, {"id": 60, "ru": "Оденьтесь потеплее.", "uz": "Iliqroq kiyining.", "ctx": "Maslahat", "gr": "Оденьтесь=kiying (buyruq shakli)."}]'::jsonb, 11),
(12, 'Ovqatlanish va ichimliklar', 'Еда и напитки', 'Ovqatlanish', 'beginner', '[{"id": 61, "ru": "Я хочу есть.", "uz": "Men ovqat yemoqchiman.", "ctx": "Istak bildirish", "gr": "хочу=xohlaman, есть=yemoq."}, {"id": 62, "ru": "Я хочу пить.", "uz": "Men ichmoqchiman.", "ctx": "Istak bildirish", "gr": "пить=ichmoq."}, {"id": 63, "ru": "Дайте мне воды.", "uz": "Menga suv bering.", "ctx": "Iltimos", "gr": "Дайте=bering (buyruq)."}, {"id": 64, "ru": "Чай, пожалуйста.", "uz": "Choy, iltimos.", "ctx": "Buyurtma", "gr": "чай=choy."}, {"id": 65, "ru": "Кофе с молоком.", "uz": "Sutli qahva.", "ctx": "Buyurtma", "gr": "с молоком=sut bilan."}, {"id": 66, "ru": "Это очень вкусно!", "uz": "Bu juda mazali!", "ctx": "Maqtov", "gr": "очень=juda, вкусно=mazali."}, {"id": 68, "ru": "Сколько стоит?", "uz": "Bu qancha turadi?", "ctx": "Narx so''rash", "gr": "Сколько=qancha, стоит=turadi."}]'::jsonb, 12),
(13, 'Asosiy harakatlar', 'Основные действия', 'Kundalik hayot', 'beginner', '[{"id": 69, "ru": "Я иду на работу.", "uz": "Men ishga ketyapman.", "ctx": "Harakat", "gr": "иду=ketyapman, на=ga (yo''nalish)."}, {"id": 70, "ru": "Я пришёл домой.", "uz": "Men uyga keldim.", "ctx": "Harakat", "gr": "пришёл=keldim (erkak). пришла=keldim (ayol)."}, {"id": 71, "ru": "Он читает книгу.", "uz": "U kitob o''qiyapti.", "ctx": "Hozirgi vaqt", "gr": "читает=o''qiyapti. Hozirgi vaqt: -ает/-яет."}, {"id": 72, "ru": "Подождите, пожалуйста.", "uz": "Iltimos, kuting.", "ctx": "Kutishni so''rash", "gr": "Подождите=kuting (buyruq)."}, {"id": 73, "ru": "Помогите, пожалуйста.", "uz": "Iltimos, yordam bering.", "ctx": "Yordam so''rash", "gr": "Eng muhim so''z!"}, {"id": 74, "ru": "Я согласен.", "uz": "Men roziman.", "ctx": "Rozilik bildirish", "gr": "согласен=roziman (erkak)."}, {"id": 75, "ru": "Где находится туалет?", "uz": "Hojatxona qayerda?", "ctx": "Joy so''rash", "gr": "Где=qayerda, находится=joylashgan."}]'::jsonb, 13),
(14, 'Restoranda ovqatlanish', 'В ресторане', 'Ovqatlanish', 'elementary', '[{"id": 93, "ru": "Столик на двоих, пожалуйста.", "uz": "Ikkilik stol, iltimos.", "ctx": "Stol so''rash", "gr": "Столик=kichik stol, двоих=ikki kishi."}, {"id": 94, "ru": "Меню, пожалуйста.", "uz": "Menyu bering, iltimos.", "ctx": "Menyu so''rash", "gr": "Menyu=ruscha so''z."}, {"id": 95, "ru": "Что вы рекомендуете?", "uz": "Nima tavsiya qilasiz?", "ctx": "Maslahat so''rash", "gr": "рекомендуете=tavsiya qilasiz."}, {"id": 96, "ru": "Я хочу заказать.", "uz": "Men buyurtma bermoqchiman.", "ctx": "Buyurtma berish", "gr": "заказать=buyurtma bermoq."}, {"id": 97, "ru": "Без сахара, пожалуйста.", "uz": "Shakarsiz, iltimos.", "ctx": "Shaxsiy so''rov", "gr": "сахара=shakarning."}, {"id": 98, "ru": "Счёт, пожалуйста.", "uz": "Hisob, iltimos.", "ctx": "Hisob so''rash", "gr": "счёт=hisob."}, {"id": 99, "ru": "Было очень вкусно!", "uz": "Juda mazali edi!", "ctx": "Maqtov", "gr": "очень=juda, вкусно=mazali."}]'::jsonb, 14),
(15, 'Taksi buyurtma berish', 'Заказ такси', 'Transport', 'elementary', '[{"id": 101, "ru": "Вы такси?", "uz": "Siz taksimisiz?", "ctx": "Tekshirish", "gr": "Такси=ruscha so''z."}, {"id": 102, "ru": "Мне нужно на вокзал.", "uz": "Menga vokzalga kerak.", "ctx": "Manzil aytish", "gr": "на=ga (yo''nalish)."}, {"id": 104, "ru": "Поехали!", "uz": "Yurdik!", "ctx": "Boshlash", "gr": "Mashhur so''z — kosmonavtlar ham aytgan!"}, {"id": 107, "ru": "Сдачи не нужно.", "uz": "Qoldiq kerak emas.", "ctx": "Choychaqa", "gr": "сдачи=qoldiqning."}, {"id": 108, "ru": "Подождите минуту.", "uz": "Bir daqiqa kuting.", "ctx": "Kutish", "gr": "минуту=bir daqiqa."}]'::jsonb, 15),
(16, 'Jamoa transporti', 'Общественный транспорт', 'Transport', 'elementary', '[{"id": 109, "ru": "Где остановка автобуса?", "uz": "Avtobus bekat qayerda?", "ctx": "Bekat so''rash", "gr": "остановка=bekat."}, {"id": 110, "ru": "Куда идёт этот автобус?", "uz": "Bu avtobus qayerga boradi?", "ctx": "Yo''nalish so''rash", "gr": "Куда=qayerga, идёт=bormoqda."}, {"id": 111, "ru": "Где станция метро?", "uz": "Metro stantsiyasi qayerda?", "ctx": "Metro so''rash", "gr": "станция=stantsiya."}, {"id": 112, "ru": "Один билет, пожалуйста.", "uz": "Bitta chipta, iltimos.", "ctx": "Chipta sotib olish", "gr": "билет=chipta."}, {"id": 113, "ru": "Два билета.", "uz": "Ikki dona chipta.", "ctx": "Chipta sotib olish", "gr": "Ikkitadan."}, {"id": 114, "ru": "Где купить билет?", "uz": "Chiptani qayerdan sotib olish mumkin?", "ctx": "Chipta joyi", "gr": "купить=sotib olmoq."}, {"id": 115, "ru": "Мне выходить.", "uz": "Men tushishim kerak.", "ctx": "Tushish", "gr": "выходить=tushmoq."}, {"id": 116, "ru": "Откройте дверь, пожалуйста.", "uz": "Eshikni oching, iltimos.", "ctx": "Eshik", "gr": "Откройте=oching, дверь=eshik."}]'::jsonb, 16),
(17, 'Klinikada', 'В поликлинике', 'Salomatlik', 'intermediate', '[{"id": 117, "ru": "Запишите меня к терапевту.", "uz": "Meni terapevtga yozing.", "ctx": "Navbat olish", "gr": "Запишите=yozing, терапевт=umumiy shifokor."}, {"id": 119, "ru": "У меня температура 38.", "uz": "Menda isitma 38.", "ctx": "Isitma", "gr": "температура=isitma."}, {"id": 121, "ru": "Я аллергик.", "uz": "Menda allergiya bor.", "ctx": "Tibbiy ma''lumot", "gr": "аллергик=allergiyasi bor."}, {"id": 122, "ru": "Два раза в день.", "uz": "Kuniga ikki marta.", "ctx": "Dozalash", "gr": "раза=marta."}, {"id": 123, "ru": "Нужен рецепт.", "uz": "Retsept kerak.", "ctx": "Retsept", "gr": "рецепт=retsept."}, {"id": 124, "ru": "Сколько стоит приём?", "uz": "Qabul qancha turadi?", "ctx": "Narx", "gr": "приём=qabul."}]'::jsonb, 17),
(18, 'Aptekada', 'В аптеке', 'Salomatlik', 'intermediate', '[{"id": 126, "ru": "От простуды.", "uz": "Shamollashdan.", "ctx": "Dori turi", "gr": "простуды=shamollashning."}, {"id": 127, "ru": "От температуры.", "uz": "Isitmadan.", "ctx": "Dori turi", "gr": "температуры=isitmaning."}, {"id": 129, "ru": "Как принимать?", "uz": "Qanday ichish kerak?", "ctx": "Qo''llanma", "gr": "принимать=qabul qilmoq/ichmoq."}, {"id": 130, "ru": "Три раза в день.", "uz": "Kuniga uch marta.", "ctx": "Qo''llanma", "gr": "Kuniga 3 marta."}, {"id": 131, "ru": "По рецепту врача.", "uz": "Shifokor retsepti bilan.", "ctx": "Retsept bilan", "gr": "врача=shifokorning."}, {"id": 132, "ru": "Проверьте срок годности.", "uz": "Yaroqlilik muddatini tekshiring.", "ctx": "Muhim", "gr": "срок годности=yaroqlilik muddati."}]'::jsonb, 18),
(19, 'Mehmonxonada', 'В гостинице', 'Turar joy', 'intermediate', '[{"id": 134, "ru": "Номер на одного.", "uz": "Bir kishilik xona.", "ctx": "Xona turi", "gr": "на одного=bir kishiga."}, {"id": 135, "ru": "Сколько стоит за ночь?", "uz": "Bir kechaga qancha?", "ctx": "Narx so''rash", "gr": "за ночь=bir kecha uchun."}, {"id": 136, "ru": "Завтрак включён?", "uz": "Nonushta kiritilganmi?", "ctx": "Xizmat so''rash", "gr": "включён=kiritilgan."}, {"id": 137, "ru": "Во сколько заселение?", "uz": "Soat nechada joylashish mumkin?", "ctx": "Kirish vaqti", "gr": "заселение=joylashish."}, {"id": 138, "ru": "Во сколько выселение?", "uz": "Soat nechada chiqish kerak?", "ctx": "Chiqish vaqti", "gr": "выселение=chiqish."}, {"id": 139, "ru": "Можно Wi-Fi пароль?", "uz": "Wi-Fi paroli bormi?", "ctx": "Internet", "gr": "пароль=parol."}, {"id": 140, "ru": "Уберите номер, пожалуйста.", "uz": "Xonani tozalang, iltimos.", "ctx": "Tozalash", "gr": "Уберите=tozalang."}]'::jsonb, 19),
(20, 'Bankda pul ishlari', 'В банке', 'Moliya', 'intermediate', '[{"id": 141, "ru": "Какой курс доллара?", "uz": "Dollar kursi qanday?", "ctx": "Kurs so''rash", "gr": "курс=kurs."}, {"id": 142, "ru": "Снять наличные.", "uz": "Naqd pul yechmoqchiman.", "ctx": "Pul yechish", "gr": "Снять=yechmoq."}, {"id": 143, "ru": "Положить на счёт.", "uz": "Hisobga kiritmoqchiman.", "ctx": "Pul kiritish", "gr": "Положить=qo''ymoq."}, {"id": 144, "ru": "Нужен паспорт.", "uz": "Pasport kerak.", "ctx": "Hujjat", "gr": "паспорт=ruscha so''z."}, {"id": 145, "ru": "Какая комиссия?", "uz": "Komissiya qancha?", "ctx": "Komissiya", "gr": "комиссия=kommisya."}, {"id": 146, "ru": "Банкомат рядом есть?", "uz": "Yaqinda bankomat bormi?", "ctx": "Bankomat", "gr": "банкомат=bankomat."}, {"id": 147, "ru": "Карта не работает.", "uz": "Karta ishlamayapti.", "ctx": "Muammo", "gr": "не работает=ishlamayapti."}]'::jsonb, 20),
(21, 'Favqulodda vaziyatlar', 'Экстренные ситуации', 'Xavfsizlik', 'intermediate', '[{"id": 149, "ru": "Помогите!", "uz": "Yordam!", "ctx": "Favqulodda", "gr": "Eng muhim so''z!"}, {"id": 150, "ru": "Вызовите полицию!", "uz": "Politsiyani chaqiring!", "ctx": "Favqulodda", "gr": "Вызовите=chaqiring."}, {"id": 151, "ru": "Вызовите скорую помощь!", "uz": "Tez yordam chaqiring!", "ctx": "Tibbiy yordam", "gr": "скорую=tez, помощью=yordam."}, {"id": 154, "ru": "Где полицейский участок?", "uz": "Politsiya bo''limi qayerda?", "ctx": "Joy so''rash", "gr": "участок=bo''lim."}, {"id": 155, "ru": "Где посольство?", "uz": "Elchixona qayerda?", "ctx": "Elchixona", "gr": "посольство=elchixona."}, {"id": 156, "ru": "Не двигайтесь!", "uz": "Qimirlamang!", "ctx": "Ko''rsatma", "gr": "Не двигайтесь=qimirlamang."}]'::jsonb, 21),
(22, 'Aeroport va samolyot', 'В аэропорту', 'Transport', 'upper', '[{"id": 164, "ru": "Вот мой паспорт.", "uz": "Mana mening pasportim.", "ctx": "Hujjat taqdim etish", "gr": "Вот=mana."}, {"id": 165, "ru": "Место у окна, пожалуйста.", "uz": "Deraza yonidagi joyni bering, iltimos.", "ctx": "Joy tanlash", "gr": "у окна=deraza yonida."}, {"id": 166, "ru": "Сколько багажа можно?", "uz": "Yuk qancha olish mumkin?", "ctx": "Yuk chegarasi", "gr": "багажа=yukning."}, {"id": 167, "ru": "Рейс задерживается.", "uz": "Reys kechiktirilmoqda.", "ctx": "Kechikish", "gr": "рейс=reys, задерживается=kechiktirilmoqda."}, {"id": 168, "ru": "Где получить багаж?", "uz": "Yukni qayerdan olish mumkin?", "ctx": "Yuk olish", "gr": "получить=olish."}, {"id": 169, "ru": "Мой багаж потерялся.", "uz": "Mening yukim yo''qoldi.", "ctx": "Muammo", "gr": "потерялся=yo''qoldi."}, {"id": 170, "ru": "Таможенный досмотр.", "uz": "Bojxona tekshiruvi.", "ctx": "Tekshiruv", "gr": "таможенный=bojxona."}]'::jsonb, 22),
(23, 'Ish va kasb', 'Работа', 'Ish', 'upper', '[{"id": 171, "ru": "Я ищу работу.", "uz": "Men ish qidiryapman.", "ctx": "Ish qidirish", "gr": "ищу=qidiryapman, работу=ishni."}, {"id": 172, "ru": "Какая зарплата?", "uz": "Maosh qancha?", "ctx": "Maosh so''rash", "gr": "зарплата=maosh."}, {"id": 173, "ru": "Пять дней в неделю.", "uz": "Haftasiga besh kun.", "ctx": "Ish vaqti", "gr": "дней=kunning, неделю=haftaning."}, {"id": 176, "ru": "Больничный.", "uz": "Kasallik varaqasi.", "ctx": "Kasallik", "gr": "больничный=kasallik varaqasi."}, {"id": 177, "ru": "Собеседование.", "uz": "Suhbat (intervyu).", "ctx": "Intervyu", "gr": "собеседование=suhbat."}, {"id": 178, "ru": "Резюме.", "uz": "Rezyume.", "ctx": "Hujjat", "gr": "Резюме=fransuzcha so''z."}]'::jsonb, 23),
(24, 'Kompyuter va texnologiya', 'Компьютер', 'Texnologiya', 'upper', '[{"id": 179, "ru": "Не работает интернет.", "uz": "Internet ishlamayapti.", "ctx": "Muammo", "gr": "не работает=ishlamayapti."}, {"id": 180, "ru": "Компьютер завис.", "uz": "Kompyuter tiqilib qoldi.", "ctx": "Muammo", "gr": "завис=tiqilib qoldi."}, {"id": 181, "ru": "Нужна программа.", "uz": "Dastur kerak.", "ctx": "Dastur", "gr": "программа=dastur."}, {"id": 182, "ru": "Пароль не подходит.", "uz": "Parol mos kelmayapti.", "ctx": "Muammo", "gr": "не подходит=mos kelmayapti."}, {"id": 183, "ru": "Скачайте файл.", "uz": "Faylni yuklab oling.", "ctx": "Yuklab olish", "gr": "Скачайте=yuklab oling."}, {"id": 184, "ru": "Отправьте на электронную почту.", "uz": "Elektron pochtangizga yuboring.", "ctx": "Email", "gr": "электронную почту=email."}, {"id": 185, "ru": "Какой у вас адрес электронной почты?", "uz": "Email manzilingiz qanday?", "ctx": "Email so''rash", "gr": "адрес=manzil."}, {"id": 186, "ru": "Экран не включается.", "uz": "Ekran yoqilmayapti.", "ctx": "Muammo", "gr": "Экран=ekran, не включается=yoqilmayapti."}]'::jsonb, 24),
(25, 'Bayramlar va tilaklar', 'Праздники', 'Kundalik hayot', 'upper', '[{"id": 195, "ru": "С Новым годом!", "uz": "Yangi yil bilan!", "ctx": "Bayram", "gr": "Новым годом=yangi yil."}, {"id": 197, "ru": "С праздником!", "uz": "Bayram bilan!", "ctx": "Bayram tabrigi", "gr": "с праздником=bayram bilan."}, {"id": 198, "ru": "Всего хорошего!", "uz": "Yaxshilar tilayman!", "ctx": "Tilak", "gr": "Всего=hammasi, хорошего=yaxshilar."}, {"id": 199, "ru": "Удачи!", "uz": "Omad!", "ctx": "Tilak", "gr": "Удачи=omad."}, {"id": 202, "ru": "Мне пора.", "uz": "Menga vaqt bo''ldi.", "ctx": "Ketish", "gr": "пора=vaqt bo''ldi."}]'::jsonb, 25)
ON CONFLICT (id) DO NOTHING;
